### ISSUE TITLE
Error "CreateDirectory"

### ISSUE THREAD

**Issue by mikados** [cecicifu/exportdede#1]
Hi,

When trying to execute the "EXE" or directly execute the file with Python, this error is obtained.
It seems something related to Selenium.
I have tested it with administrator permissions.

**SO:** Windows 10 (2004 x64)
**Chrome:** 85.0.4183.102 (x64)

Thanks for the project!

![Error](https://user-images.githubusercontent.com/8138158/93719310-e7691d00-fb81-11ea-9aeb-5659677122d5.png)

**Comment by cecicifu** [comment]
Hi, i tried it on a clean windows installation (without Python installed) and works fine, you previusly haved 60 second left to login when Google Chrome opens, but recently i updated the timeout to 5 minutes. Can u try it now ? Thanks you. :D

**Comment by mikados** [comment]
Hi,

i just did "pull" and i get the same error, both with exe version and direct python version.

**Comment by cecicifu** [comment]
Hi, do you have Mozilla Firefox installed ? can you try running it with this browser?
[https://github.com/cecicifu/exportdede/releases/download/1.0/exportdede_firefox.zip](url)

Thanks u. Regards.

**Comment by mikados** [comment]
Now if it works fine! 

It would be interesting of the series, that the application tells you which was the last chapter you have seen.

Thank you!!!

**Comment by cecicifu** [comment]
Nice! I'll keep that in mind for the next updates.

Thanks! :D
